package handlers

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/joho/godotenv"
	"github.com/labstack/echo/v4"
	"golang.org/x/crypto/bcrypt"
	"net/http/httptest"
	"net/url"
	"os"
	"skillmatch/database"
	auth "skillmatch/middleware"
	"skillmatch/models"
	"strings"
	"testing"
	"time"
)

// Opt in with SKILLMATCH_INTEGRATION=1. Fixtures live only in a unique test schema.
func TestMatchingAPIIntegration(t *testing.T) {
	if os.Getenv("SKILLMATCH_INTEGRATION") != "1" {
		t.Skip("set SKILLMATCH_INTEGRATION=1 to test against PostgreSQL")
	}
	_ = godotenv.Load("../.env")
	ctx := context.Background()
	admin, err := pgxpool.New(ctx, os.Getenv("DATABASE_URL"))
	if err != nil {
		t.Fatal(err)
	}
	defer admin.Close()
	schema := fmt.Sprintf("skillmatch_test_%d", time.Now().UnixNano())
	quoted := pgx.Identifier{schema}.Sanitize()
	if _, err := admin.Exec(ctx, "CREATE SCHEMA "+quoted); err != nil {
		t.Fatal(err)
	}
	defer func() {
		if _, err := admin.Exec(ctx, "DROP SCHEMA "+quoted+" CASCADE"); err != nil {
			t.Error(err)
		}
	}()
	config, err := pgxpool.ParseConfig(os.Getenv("DATABASE_URL"))
	if err != nil {
		t.Fatal(err)
	}
	config.ConnConfig.RuntimeParams["search_path"] = schema
	pool, err := pgxpool.NewWithConfig(ctx, config)
	if err != nil {
		t.Fatal(err)
	}
	defer pool.Close()
	// Existing schema, before any new columns. No public user/team records are modified.
	_, err = pool.Exec(ctx, `
 CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR NOT NULL, email VARCHAR UNIQUE NOT NULL, password TEXT NOT NULL, bio TEXT, experience_level VARCHAR NOT NULL);
 CREATE TABLE teams (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR NOT NULL, description TEXT, project_idea TEXT, owner_id BIGINT REFERENCES users(id) NOT NULL, max_members INTEGER NOT NULL);
 CREATE TABLE team_roles (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, team_id BIGINT REFERENCES teams(id) NOT NULL, role_name VARCHAR NOT NULL, status VARCHAR NOT NULL DEFAULT 'open', UNIQUE(team_id, role_name));
 CREATE TABLE team_members (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, team_id BIGINT REFERENCES teams(id) NOT NULL, user_id BIGINT REFERENCES users(id) NOT NULL, role VARCHAR NOT NULL, UNIQUE(team_id,user_id));
 CREATE TABLE skills (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR UNIQUE NOT NULL);
 CREATE TABLE role_skills (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, role_id BIGINT REFERENCES team_roles(id) NOT NULL, skill_id BIGINT REFERENCES skills(id) NOT NULL, required_level VARCHAR NOT NULL DEFAULT 'beginner', UNIQUE(role_id,skill_id));
 CREATE TABLE user_skills (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT REFERENCES users(id) NOT NULL, skill_id BIGINT REFERENCES skills(id) NOT NULL, level VARCHAR NOT NULL, UNIQUE(user_id,skill_id));
 CREATE TABLE join_requests (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, team_id BIGINT REFERENCES teams(id) NOT NULL, user_id BIGINT REFERENCES users(id) NOT NULL, message TEXT, status VARCHAR NOT NULL DEFAULT 'pending', UNIQUE(team_id,user_id));
 `)
	if err != nil {
		t.Fatal(err)
	}
	hash, _ := bcrypt.GenerateFromPassword([]byte("test-password"), bcrypt.MinCost)
	var oldID int64
	if err := pool.QueryRow(ctx, `INSERT INTO users(name,email,password,experience_level) VALUES ('Legacy user','legacy@example.test',$1,'Beginner') RETURNING id`, string(hash)).Scan(&oldID); err != nil {
		t.Fatal(err)
	}
	var oldTeam, oldRole int64
	if err := pool.QueryRow(ctx, `INSERT INTO teams(name,owner_id,max_members) VALUES ('Legacy team',$1,4) RETURNING id`, oldID).Scan(&oldTeam); err != nil {
		t.Fatal(err)
	}
	if err := pool.QueryRow(ctx, `INSERT INTO team_roles(team_id,role_name) VALUES ($1,'Frontend Developer') RETURNING id`, oldTeam).Scan(&oldRole); err != nil {
		t.Fatal(err)
	}
	var oldSkill int64
	if err := pool.QueryRow(ctx, `INSERT INTO skills(name) VALUES ('React') RETURNING id`).Scan(&oldSkill); err != nil {
		t.Fatal(err)
	}
	for range 2 {
		if err := database.Migrate(ctx, pool); err != nil {
			t.Fatal(err)
		}
	}
	var preservedSkill int64
	if err := pool.QueryRow(ctx, `SELECT id FROM skills WHERE name='React' AND category='Technical'`).Scan(&preservedSkill); err != nil || preservedSkill != oldSkill {
		t.Fatal("existing skill ID was not preserved and categorized")
	}

	e := echo.New()
	wrap := func(fn func(echo.Context, *pgxpool.Pool) error) echo.HandlerFunc {
		return func(c echo.Context) error { return fn(c, pool) }
	}
	e.POST("/api/login", wrap(Login))
	e.POST("/api/register", wrap(Register))
	e.GET("/api/teams", wrap(GetTeams))
	e.GET("/api/skills", wrap(GetSkills))
	e.GET("/api/teams/search", wrap(SearchTeams))
	e.GET("/api/teams/:id", wrap(GetTeamDetail))
	e.GET("/api/teams/:id/roles", wrap(GetTeamRoles))
	protected := e.Group("/api", auth.AuthMiddleware)
	protected.GET("/profile", wrap(GetUserProfile))
	protected.PUT("/profile", wrap(UpdateProfile))
	protected.POST("/teams", wrap(CreateTeam))
	protected.PUT("/teams/:id", wrap(UpdateTeam))
	protected.POST("/teams/:id/roles", wrap(CreateTeamRole))
	protected.PUT("/teams/:id/roles/:role_id", wrap(UpdateTeamRole))
	protected.GET("/teams/:id/roles/:role_id/match", wrap(GetRoleMatch))
	protected.POST("/teams/:id/join", wrap(JoinTeam))
	protected.GET("/teams/:id/join-requests", wrap(GetJoinRequests))
	protected.POST("/profile/skills", wrap(AddProfileSkill))
	protected.GET("/profile/skills", wrap(GetProfileSkills))
	protected.PUT("/profile/skills/:skill_id", wrap(UpdateProfileSkill))
	protected.DELETE("/profile/skills/:skill_id", wrap(DeleteProfileSkill))
	e.GET("/api/teams/:id/roles/:role_id/skills", wrap(GetRoleSkills))
	protected.POST("/teams/:id/roles/:role_id/skills", wrap(AddRoleSkill))
	call := func(method, path, body, token string, want int) []byte {
		t.Helper()
		req := httptest.NewRequest(method, path, strings.NewReader(body))
		req.Header.Set("Content-Type", "application/json")
		if token != "" {
			req.Header.Set("Authorization", "Bearer "+token)
		}
		rec := httptest.NewRecorder()
		e.ServeHTTP(rec, req)
		if rec.Code != want {
			t.Fatalf("%s %s: got %d want %d: %s", method, path, rec.Code, want, rec.Body.String())
		}
		return rec.Body.Bytes()
	}
	decode := func(data []byte, target any) {
		t.Helper()
		if err := json.Unmarshal(data, target); err != nil {
			t.Fatal(err)
		}
	}
	var login struct{ Token string }
	decode(call("POST", "/api/login", `{"email":"legacy@example.test","password":"test-password"}`, "", 200), &login)
	token := login.Token
	call("POST", "/api/login", `{"email":"legacy@example.test","password":"wrong"}`, "", 401)
	call("GET", "/api/profile", "", "", 401)
	var profile models.User
	decode(call("GET", "/api/profile", "", token, 200), &profile)
	if profile.ID != oldID || profile.PreferredRole != "" || profile.Availability != "" || profile.ProjectInterest != "" {
		t.Fatalf("legacy profile changed: %+v", profile)
	}
	var teams []models.Team
	decode(call("GET", "/api/teams", "", "", 200), &teams)
	if len(teams) != 1 || teams[0].BeginnerFriendly || teams[0].WillingToMentor || teams[0].CompetitionCategory != "" || teams[0].CompetitionType != "" {
		t.Fatal("legacy teams/defaults not preserved")
	}
	call("GET", fmt.Sprintf("/api/teams/%d", oldTeam), "", "", 200)
	var roles []models.TeamRole
	decode(call("GET", fmt.Sprintf("/api/teams/%d/roles", oldTeam), "", "", 200), &roles)
	if len(roles) != 1 || roles[0].ExperiencePreference != "open" {
		t.Fatal("legacy role missing open default")
	}
	var match models.RoleMatchResponse
	matchPath := fmt.Sprintf("/api/teams/%d/roles/%d/match", oldTeam, oldRole)
	decode(call("GET", matchPath, "", token, 200), &match)
	if !match.ProfileIncomplete || match.MatchScore != 71 {
		t.Fatalf("legacy neutral match: %+v", match)
	}

	call("PUT", "/api/profile", `{"name":"Legacy user","bio":"Updated","experience_level":"beginner","preferred_role":"Frontend Developer","availability":"flexible","project_interest":"Web Development"}`, token, 200)
	// Old requests leave new preferences intact; explicit empty strings clear them.
	call("PUT", "/api/profile", `{"name":"Legacy user","bio":"Updated again","experience_level":"Beginner"}`, token, 200)
	decode(call("GET", "/api/profile", "", token, 200), &profile)
	if profile.PreferredRole != "Frontend Developer" || profile.Availability != "flexible" || profile.ProjectInterest != "Web Development" {
		t.Fatal("profile preferences did not persist")
	}
	call("PUT", "/api/profile", `{"name":"Legacy user","experience_level":"Beginner","availability":"night"}`, token, 400)
	call("PUT", "/api/profile", fmt.Sprintf(`{"name":"Legacy user","experience_level":"Beginner","preferred_role":%q}`, strings.Repeat("x", 101)), token, 400)

	var created struct {
		TeamID int64 `json:"team_id"`
		RoleID int64 `json:"role_id"`
	}
	call("POST", "/api/teams", `{"name":"Old client team","project_idea":"Project","max_members":4}`, token, 201)
	decode(call("POST", "/api/teams", `{"name":"HackSquad","description":"Learn together","project_idea":"Web Development","max_members":5,"beginner_friendly":true,"willing_to_mentor":true}`, token, 201), &created)
	teamID := created.TeamID
	teamPath := fmt.Sprintf("/api/teams/%d", teamID)
	var ownerCount int
	if err := pool.QueryRow(ctx, `SELECT COUNT(*) FROM team_members WHERE team_id=$1 AND user_id=$2`, teamID, oldID).Scan(&ownerCount); err != nil || ownerCount != 1 {
		t.Fatal("team owner membership missing")
	}
	decode(call("POST", teamPath+"/roles", `{"role_name":"Frontend Developer","experience_preference":"beginner"}`, token, 201), &created)
	roleID := created.RoleID
	rolePath := fmt.Sprintf("%s/roles/%d", teamPath, roleID)
	call("POST", teamPath+"/roles", `{"role_name":"Other"}`, token, 201)
	call("POST", teamPath+"/roles", `{"role_name":"Invalid","experience_preference":"expert"}`, token, 400)
	call("PUT", rolePath, `{"experience_preference":"expert"}`, token, 400)
	call("PUT", rolePath, `{"status":"filled"}`, token, 200)
	call("PUT", rolePath, `{"experience_preference":"advanced"}`, token, 200)
	decode(call("GET", teamPath+"/roles", "", "", 200), &roles)
	if roles[0].Status != "filled" || roles[0].ExperiencePreference != "advanced" {
		t.Fatal("role update overwrote unrelated fields")
	}
	call("PUT", rolePath, `{"status":"open","experience_preference":"beginner"}`, token, 200)
	for _, name := range []string{"React", "JavaScript", "TypeScript"} {
		var skillID int64
		if err := pool.QueryRow(ctx, `SELECT id FROM skills WHERE name=$1`, name).Scan(&skillID); err != nil {
			t.Fatal(err)
		}
		required := "beginner"
		if name == "React" {
			required = "intermediate"
		}
		call("POST", rolePath+"/skills", fmt.Sprintf(`{"skill_id":%d,"required_level":%q}`, skillID, required), token, 200)
		if name != "TypeScript" {
			call("POST", "/api/profile/skills", fmt.Sprintf(`{"skill_id":%d,"level":"beginner"}`, skillID), token, 201)
		}
	}
	decode(call("GET", rolePath+"/match", "", token, 200), &match)
	if match.MatchScore != 88 || match.ExperienceFitScore != 10 || !match.BeginnerFriendly || !match.WillingToMentor || match.ProfileIncomplete {
		t.Fatalf("case A API result: %+v", match)
	}
	call("PUT", "/api/profile", `{"name":"Legacy user","experience_level":"Advanced"}`, token, 200)
	decode(call("GET", rolePath+"/match", "", token, 200), &match)
	if match.ExperienceFitScore != 5 {
		t.Fatal("case B failed")
	}
	call("PUT", "/api/profile", `{"name":"Legacy user","experience_level":"Beginner"}`, token, 200)
	call("PUT", rolePath, `{"experience_preference":"advanced"}`, token, 200)
	decode(call("GET", rolePath+"/match", "", token, 200), &match)
	if match.ExperienceFitScore != 3 || match.MatchScore != 81 {
		t.Fatal("case C failed")
	}
	call("PUT", rolePath, `{"experience_preference":"open"}`, token, 200)
	decode(call("GET", rolePath+"/match", "", token, 200), &match)
	if match.ExperienceFitScore != 10 {
		t.Fatal("case D failed")
	}
	call("GET", fmt.Sprintf("/api/teams/%d/roles/%d/match", oldTeam, roleID), "", token, 404)

	decode(call("GET", "/api/teams/search?name=hack&role=frontend&skill=React&beginner_friendly=true", "", "", 200), &teams)
	if len(teams) != 1 || teams[0].ID != teamID || !teams[0].BeginnerFriendly || !teams[0].WillingToMentor {
		t.Fatal("combined filters failed")
	}
	decode(call("GET", "/api/teams/search?beginner_friendly=false", "", "", 200), &teams)
	if len(teams) != 2 {
		t.Fatal("false filter failed")
	}
	decode(call("GET", "/api/teams/search", "", "", 200), &teams)
	if len(teams) != 3 {
		t.Fatal("absent filter must include all teams")
	}
	call("GET", "/api/teams/search?beginner_friendly=invalid", "", "", 400)
	call("PUT", teamPath, `{"name":"HackSquad","project_idea":"Web Development","max_members":5,"beginner_friendly":false,"willing_to_mentor":false}`, token, 200)
	decode(call("GET", "/api/teams/search?beginner_friendly=true", "", "", 200), &teams)
	if len(teams) != 0 {
		t.Fatal("team checkbox update failed")
	}

	call("POST", "/api/register", `{"name":"Another user","email":"other@example.test","password":"test-password","experience_level":"beginner"}`, "", 201)
	decode(call("POST", "/api/login", `{"email":"other@example.test","password":"test-password"}`, "", 200), &login)
	call("PUT", teamPath, `{"name":"Not owner","project_idea":"Project","max_members":4}`, login.Token, 403)
	call("POST", teamPath+"/roles", `{"role_name":"Not owner"}`, login.Token, 403)
	call("PUT", rolePath, `{"experience_preference":"beginner"}`, login.Token, 403)
	call("POST", teamPath+"/join", `{"message":"I would like to learn"}`, login.Token, 201)
	call("GET", teamPath+"/join-requests", "", token, 200)
	call("GET", teamPath+"/join-requests", "", login.Token, 403)
	call("PUT", "/api/profile", `{"name":"Legacy user","experience_level":"Beginner","preferred_role":"","availability":"","project_interest":""}`, token, 200)
	decode(call("GET", "/api/profile", "", token, 200), &profile)
	if profile.PreferredRole != "" || profile.Availability != "" || profile.ProjectInterest != "" {
		t.Fatal("optional fields did not clear")
	}
	// Verify database constraints independently of HTTP validation.
	if _, err := pool.Exec(ctx, `UPDATE team_roles SET experience_preference='expert' WHERE id=$1`, roleID); err == nil {
		t.Fatal("missing experience database constraint")
	}
	if _, err := pool.Exec(ctx, `UPDATE users SET availability='night' WHERE id=$1`, oldID); err == nil {
		t.Fatal("missing availability database constraint")
	}
	// Every competition uses the same authenticated profile -> role -> skill flow.
	var catalog []models.Skill
	decode(call("GET", "/api/skills", "", "", 200), &catalog)
	if len(catalog) != 59 {
		t.Fatalf("catalog should contain 59 unique skills, got %d", len(catalog))
	}
	var communication []models.Skill
	decode(call("GET", "/api/skills?category=Communication", "", "", 200), &communication)
	if len(communication) != 7 {
		t.Fatalf("communication category: %+v", communication)
	}
	for _, skill := range communication {
		if skill.Category != "Communication" {
			t.Fatal("category missing")
		}
	}
	for _, scenario := range []struct {
		category, kind, role string
		skills               []string
	}{
		{"Academic", "Debate", "Second Speaker", []string{"Public Speaking", "Argumentation", "Rebuttal", "Critical Thinking"}},
		{"Business", "Business Case", "Business Analyst", []string{"Business Analysis", "Market Research", "Strategy", "Presentation"}},
		{"Research", "Scientific Writing", "Academic Writer", []string{"Academic Writing", "Research", "Literature Review"}},
		{"Creative", "Video Competition", "Video Editor", []string{"Video Editing", "Storytelling"}},
		{"Technology", "Hackathon", "Backend Developer", []string{"Go", "Figma", "PostgreSQL"}},
		{"Other", "Custom Challenge", "Custom Role", []string{"Team Communication"}},
	} {
		t.Run(scenario.kind, func(t *testing.T) {
			body := fmt.Sprintf(`{"name":"Competition fixture","project_idea":"Prepare together","max_members":3,"competition_category":%q,"competition_type":%q,"beginner_friendly":true,"willing_to_mentor":true}`, scenario.category, scenario.kind)
			decode(call("POST", "/api/teams", body, token, 201), &created)
			path := fmt.Sprintf("/api/teams/%d", created.TeamID)
			decode(call("POST", path+"/roles", fmt.Sprintf(`{"role_name":%q}`, scenario.role), token, 201), &created)
			rp := fmt.Sprintf("%s/roles/%d", path, created.RoleID)
			call("PUT", "/api/profile", fmt.Sprintf(`{"name":"Legacy user","experience_level":"beginner","preferred_role":%q,"availability":"flexible","project_interest":%q}`, scenario.role, scenario.kind), token, 200)
			for _, name := range scenario.skills {
				var skillID int64
				for _, skill := range catalog {
					if skill.Name == name {
						skillID = skill.ID
					}
				}
				if skillID == 0 {
					t.Fatalf("missing seed %s", name)
				}
				call("POST", "/api/profile/skills", fmt.Sprintf(`{"skill_id":%d,"level":"beginner"}`, skillID), token, 201)
				call("POST", rp+"/skills", fmt.Sprintf(`{"skill_id":%d,"required_level":"intermediate"}`, skillID), token, 200)
				call("PUT", fmt.Sprintf("/api/profile/skills/%d", skillID), `{"level":"intermediate"}`, token, 200)
			}
			var requirements []models.RoleSkill
			decode(call("GET", rp+"/skills", "", "", 200), &requirements)
			if len(requirements) != len(scenario.skills) {
				t.Fatal("required skills missing")
			}
			decode(call("GET", rp+"/match", "", token, 200), &match)
			if match.MatchScore != 100 || match.SkillScore != 30 || match.ExperienceFitScore != 10 || !match.BeginnerFriendly {
				t.Fatalf("generic match: %+v", match)
			}
			var detail struct {
				Team models.Team `json:"team"`
			}
			decode(call("GET", path, "", "", 200), &detail)
			if detail.Team.CompetitionCategory != scenario.category || detail.Team.CompetitionType != scenario.kind {
				t.Fatal("detail competition missing")
			}
			query := "/api/teams/search?competition_category=" + url.QueryEscape(scenario.category) + "&competition_type=" + url.QueryEscape(scenario.kind) + "&skill=" + url.QueryEscape(scenario.skills[0]) + "&role=" + url.QueryEscape(scenario.role) + "&beginner_friendly=true"
			decode(call("GET", query, "", "", 200), &teams)
			if len(teams) != 1 || teams[0].ID != detail.Team.ID {
				t.Fatalf("combined category/type/role/skill/beginner filter: %+v", teams)
			}
			// An older client must not erase competition metadata.
			call("PUT", path, `{"name":"Updated fixture","project_idea":"Prepare together","max_members":3}`, token, 200)
			decode(call("GET", path, "", "", 200), &detail)
			if detail.Team.CompetitionType != scenario.kind {
				t.Fatal("old update erased competition")
			}
			call("PUT", path, body, login.Token, 403)
			call("PUT", path, `{"name":"Updated fixture","project_idea":"Prepare together","max_members":3,"competition_category":"Other","competition_type":"New custom type"}`, token, 200)
			decode(call("GET", path, "", "", 200), &detail)
			if detail.Team.CompetitionCategory != "Other" || detail.Team.CompetitionType != "New custom type" {
				t.Fatal("competition edit failed")
			}
			call("PUT", path, `{"name":"Updated fixture","project_idea":"Prepare together","max_members":3,"competition_category":"","competition_type":""}`, token, 200)
			decode(call("GET", path, "", "", 200), &detail)
			if detail.Team.CompetitionCategory != "" || detail.Team.CompetitionType != "" {
				t.Fatal("explicit clear failed")
			}
			var owned []models.UserSkill
			decode(call("GET", "/api/profile/skills", "", token, 200), &owned)
			for _, skill := range owned {
				if skill.Category == "" {
					t.Fatal("profile skill lacks category")
				}
			}
			for _, requirement := range requirements {
				call("DELETE", fmt.Sprintf("/api/profile/skills/%d", requirement.SkillID), "", token, 200)
			}
		})
	}
	call("POST", "/api/teams", fmt.Sprintf(`{"name":"Invalid","project_idea":"Goal","max_members":3,"competition_type":%q}`, strings.Repeat("x", 101)), token, 400)
	call("PUT", teamPath, fmt.Sprintf(`{"name":"HackSquad","project_idea":"Goal","max_members":3,"competition_category":%q}`, strings.Repeat("x", 51)), token, 400)
	// Normalize only for duplicate detection; preserve historical spellings and custom categories.
	if _, err := pool.Exec(ctx, `UPDATE skills SET name=' public speaking ' WHERE name='Public Speaking'; UPDATE skills SET category='Custom Category' WHERE name='React'`); err != nil {
		t.Fatal(err)
	}
	if err := database.Migrate(ctx, pool); err != nil {
		t.Fatal(err)
	}
	decode(call("GET", "/api/skills", "", "", 200), &catalog)
	if len(catalog) != 59 {
		t.Fatal("migration inserted a case/whitespace duplicate")
	}
	for _, skill := range catalog {
		if skill.ID == oldSkill && skill.Category != "Custom Category" {
			t.Fatal("custom category overwritten")
		}
	}
	if _, err := pool.Exec(ctx, `INSERT INTO skills(name) VALUES ('Unclassified legacy skill')`); err != nil {
		t.Fatal(err)
	}
	decode(call("GET", "/api/skills?category=Other", "", "", 200), &catalog)
	if len(catalog) != 1 || catalog[0].Category != "Other" {
		t.Fatal("null skill category fallback failed")
	}
	// A failure to add the owner must roll back team creation as well.
	if _, err := pool.Exec(ctx, `ALTER TABLE team_members ADD CONSTRAINT test_reject_owner CHECK (role <> 'Owner') NOT VALID`); err != nil {
		t.Fatal(err)
	}
	call("POST", "/api/teams", `{"name":"Rollback fixture","project_idea":"Project","max_members":4}`, token, 500)
	var failedTeams int
	if err := pool.QueryRow(ctx, `SELECT COUNT(*) FROM teams WHERE name='Rollback fixture'`).Scan(&failedTeams); err != nil || failedTeams != 0 {
		t.Fatal("failed owner membership left an orphan team")
	}
}
