import { Link } from 'react-router-dom'
import { getCurrentUserId } from '../../utils/auth'

export default function TeamReadinessPreview({ team, readiness, error, retry }) {
  const owner = Number(team.owner_id) === getCurrentUserId()
  if (error) return <div className="command-readiness"><h3>Team Readiness</h3><p className="command-inline-error" role="alert">Readiness couldn't be loaded. <button onClick={retry}>Retry</button></p></div>
  if (!readiness || readiness.status === 'setup_required' || readiness.readiness_score == null) return <div className="command-readiness readiness-setup"><h3>Readiness setup incomplete</h3><p>Define roles and required skills to analyze your team.</p><Link className="button button-secondary" to={`/teams/${team.id}?tab=roles`}>{owner ? 'Set Up Team Roles' : 'View Team'}</Link></div>
  return <div className="command-readiness"><div className="readiness-overview"><div className="readiness-ring-block"><h3>Team Readiness</h3><div className="readiness-ring" role="img" aria-label={`${readiness.readiness_score}% team readiness`}><svg viewBox="0 0 120 120" aria-hidden="true"><circle className="ring-track" cx="60" cy="60" r="49" /><circle className="ring-value" cx="60" cy="60" r="49" pathLength="100" strokeDasharray={`${readiness.readiness_score} 100`} /></svg><strong>{readiness.readiness_score}%</strong></div><p>Measured from team data</p></div><div className="readiness-areas"><h3>Key strengths</h3><div className="command-tags">{readiness.strengths?.length ? readiness.strengths.slice(0, 3).map(name => <span key={name}>{name}</span>) : <p>No required skills fully covered yet.</p>}</div><h3>Priority areas</h3><div className="command-tags priority-tags">{readiness.priority_gaps?.length ? readiness.priority_gaps.slice(0, 3).map((gap, index) => <span key={`${gap.type}-${index}`}>{gap.name}</span>) : <p>All configured requirements covered.</p>}</div></div></div><Link className="readiness-detail-link" to={`/teams/${team.id}?tab=readiness`}>View Readiness Details <span>→</span></Link></div>
}
