-- Additive and repeatable; existing team values stay NULL until their owner edits them.
ALTER TABLE teams
    ADD COLUMN IF NOT EXISTS competition_category VARCHAR(50),
    ADD COLUMN IF NOT EXISTS competition_type VARCHAR(100);
ALTER TABLE skills ADD COLUMN IF NOT EXISTS category VARCHAR(50);

-- Serialize catalog inserts with other writers; keep all existing IDs and names.
LOCK TABLE skills IN SHARE ROW EXCLUSIVE MODE;
WITH catalog(name, category) AS (VALUES
    ('Frontend Development', 'Technical'),
    ('Backend Development', 'Technical'),
    ('React', 'Technical'),
    ('JavaScript', 'Technical'),
    ('TypeScript', 'Technical'),
    ('Go', 'Technical'),
    ('Python', 'Technical'),
    ('PostgreSQL', 'Technical'),
    ('API Integration', 'Technical'),
    ('Git', 'Technical'),
    ('Docker', 'Technical'),
    ('Public Speaking', 'Communication'),
    ('Argumentation', 'Communication'),
    ('Rebuttal', 'Communication'),
    ('Presentation', 'Communication'),
    ('Negotiation', 'Communication'),
    ('Team Communication', 'Communication'),
    ('Persuasive Speaking', 'Communication'),
    ('Research', 'Research'),
    ('Literature Review', 'Research'),
    ('Critical Thinking', 'Research'),
    ('Data Analysis', 'Research'),
    ('Academic Writing', 'Research'),
    ('Citation Management', 'Research'),
    ('Problem Analysis', 'Research'),
    ('Business Analysis', 'Business'),
    ('Market Research', 'Business'),
    ('Financial Analysis', 'Business'),
    ('Strategy', 'Business'),
    ('Pitching', 'Business'),
    ('Business Modeling', 'Business'),
    ('Marketing', 'Business'),
    ('Competitor Analysis', 'Business'),
    ('Figma', 'Design'),
    ('UI Design', 'Design'),
    ('UX Research', 'Design'),
    ('Adobe Illustrator', 'Design'),
    ('Photoshop', 'Design'),
    ('Typography', 'Design'),
    ('Branding', 'Design'),
    ('Poster Design', 'Design'),
    ('Storytelling', 'Creative'),
    ('Scriptwriting', 'Creative'),
    ('Video Editing', 'Creative'),
    ('Cinematography', 'Creative'),
    ('Voice Over', 'Creative'),
    ('Motion Graphics', 'Creative'),
    ('Photography', 'Creative'),
    ('Leadership', 'Leadership'),
    ('Team Coordination', 'Leadership'),
    ('Project Management', 'Leadership'),
    ('Decision Making', 'Leadership'),
    ('Time Management', 'Leadership'),
    ('English', 'Language'),
    ('Indonesian', 'Language'),
    ('Copywriting', 'Language'),
    ('Case Building', 'Strategy'),
    ('Game Strategy', 'Strategy'),
    ('Analytical Thinking', 'Strategy')
)
INSERT INTO skills(name, category)
SELECT c.name, c.category FROM catalog c
WHERE NOT EXISTS (SELECT 1 FROM skills s WHERE LOWER(TRIM(s.name)) = LOWER(c.name))
ON CONFLICT DO NOTHING;

-- Only fill unclassified known skills; preserve custom categories.
WITH catalog(name, category) AS (VALUES
    ('Frontend Development', 'Technical'),
    ('Backend Development', 'Technical'),
    ('React', 'Technical'),
    ('JavaScript', 'Technical'),
    ('TypeScript', 'Technical'),
    ('Go', 'Technical'),
    ('Python', 'Technical'),
    ('PostgreSQL', 'Technical'),
    ('API Integration', 'Technical'),
    ('Git', 'Technical'),
    ('Docker', 'Technical'),
    ('Public Speaking', 'Communication'),
    ('Argumentation', 'Communication'),
    ('Rebuttal', 'Communication'),
    ('Presentation', 'Communication'),
    ('Negotiation', 'Communication'),
    ('Team Communication', 'Communication'),
    ('Persuasive Speaking', 'Communication'),
    ('Research', 'Research'),
    ('Literature Review', 'Research'),
    ('Critical Thinking', 'Research'),
    ('Data Analysis', 'Research'),
    ('Academic Writing', 'Research'),
    ('Citation Management', 'Research'),
    ('Problem Analysis', 'Research'),
    ('Business Analysis', 'Business'),
    ('Market Research', 'Business'),
    ('Financial Analysis', 'Business'),
    ('Strategy', 'Business'),
    ('Pitching', 'Business'),
    ('Business Modeling', 'Business'),
    ('Marketing', 'Business'),
    ('Competitor Analysis', 'Business'),
    ('Figma', 'Design'),
    ('UI Design', 'Design'),
    ('UX Research', 'Design'),
    ('Adobe Illustrator', 'Design'),
    ('Photoshop', 'Design'),
    ('Typography', 'Design'),
    ('Branding', 'Design'),
    ('Poster Design', 'Design'),
    ('Storytelling', 'Creative'),
    ('Scriptwriting', 'Creative'),
    ('Video Editing', 'Creative'),
    ('Cinematography', 'Creative'),
    ('Voice Over', 'Creative'),
    ('Motion Graphics', 'Creative'),
    ('Photography', 'Creative'),
    ('Leadership', 'Leadership'),
    ('Team Coordination', 'Leadership'),
    ('Project Management', 'Leadership'),
    ('Decision Making', 'Leadership'),
    ('Time Management', 'Leadership'),
    ('English', 'Language'),
    ('Indonesian', 'Language'),
    ('Copywriting', 'Language'),
    ('Case Building', 'Strategy'),
    ('Game Strategy', 'Strategy'),
    ('Analytical Thinking', 'Strategy')
)
UPDATE skills s SET category = c.category FROM catalog c
WHERE LOWER(TRIM(s.name)) = LOWER(c.name) AND (s.category IS NULL OR TRIM(s.category) = '');
